	case 1: if( SpaceCounts ) RETURN;
		break;
	case 2: Lexval.i=getoct(P_TEXT+2);RETURN;
		break;
	case 3: Lexval.i=getnum(P_TEXT+1);RETURN;
		break;
	case 4: Lexval.i=gethex(P_TEXT+2);RETURN;
		break;
	case 5: Lexval.i=backslash(P_TEXT+1);RETURN;
		break;
	case 6: Lexval.p = P_TEXT; RETURN;
		break;
	case 7: DefMacro(P_TEXT+1,P_LEN-1);													 RETURN;
		break;
	case 8: ExpandMacro( parstab );
		break;
	case 9: Lexval.p=Counter(parstab,P_TEXT);													 RETURN;
		break;
	case 10: RETURN;
		break;
	case 11: RETURN;
		break;
	case 12: RETURN;
		break;
	case 13: RETURN;
		break;
	case 14: RETURN;
		break;
	case 15: RETURN;
		break;
	case 16: RETURN;
		break;
	case 17: RETURN;
		break;
	case 18: RETURN;
		break;
	case 19: RETURN;
		break;
	case 20: RETURN;
		break;
	case 21: Lexval.i = (IgnoreCase?WideLowerCase( WideString( *P_TEXT ))[ 1 ]:*P_TEXT); RETURN;
		break;
